### ISSUE TITLE
Querying /deltaTree takes exponentially longer with larger number of modules

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#117]
The Analyzer takes exponentially longer with increasing number of modules in a project.

**Comment by thombergs** [comment]
I did a full analysis of the coderadar project with all 7 gradle modules added as modules via the REST API. I did not observe an overly long analyzing duration. Also, the /deltaTree endpoint returned metrics in acceptable time (a couple seconds, which is not longer than without modules).

@pschild: could you elaborate on the performance problems you observed, so I can try to reproduce?

**Comment by thombergs** [comment]
Assumption: the time for analyzing a project is not affected by the number of modules, but the time for querying the /deltaTree endpoint.

**Comment by pschild** [comment]
The issue seems not to have sth. to do with any modules. I could observe an increasing of the time between single "associating"-jobs and at this point of time, no modules were saved at all.

I did a test with the JUnit repo: https://github.com/junit-team/junit4
You can have a look at the timestamps to see how the time increased.

At the beginning, the jobs ran through very quickly:
`2017-02-01 19:45:26.387...starting associating files of commit...`
`2017-02-01 19:45:26.539...starting associating files of commit...`
`2017-02-01 19:45:26.604...starting associating files of commit...`
`2017-02-01 19:45:26.675...starting associating files of commit...`
`...`

After one hour:
`2017-02-01 20:45:19.306...starting associating files of commit...`
`2017-02-01 20:45:35.686...starting associating files of commit...`
`2017-02-01 20:45:53.483...starting associating files of commit...`
`2017-02-01 20:46:12.810...starting associating files of commit...`
`...`

The last ones before cancelling:
`2017-02-01 21:26:30.677...starting associating files of commit...`
`2017-02-01 21:26:59.593...starting associating files of commit...`
`2017-02-01 21:27:34.463...starting associating files of commit...`
`2017-02-01 21:28:04.770...starting associating files of commit...`
`...`

When I cancelled, there were 1.189 of 2.159 commits merged (merged = 1), and 970 were still to be done (merged = 0).

For the deltaTree endpoint I will do another test ;-)

**Comment by thombergs** [comment]
Moving discussion of slow file association to issue #156 .

**Comment by pschild** [comment]
Hi,

regarding the performance of querying the deltaTree endpoint, I did some tests with my visualization tool (in the browser) for the project Coderadar itself:

Without any module the querying time is around 2,8s.
After adding the module "coderadar-server", querying time is around 9,3s.
After adding the module "coderadar-plugins", querying time is around 9,9s.
After adding the module "coderadar-plugin-api", querying time is around 10,1s.
After adding the 4 plugin modules, querying time is around 10,1s.

So the time increased by adding modules and there should be done some optimization in order to handle bigger projects as well :)

**Comment by thombergs** [comment]
Try again with the current version, please. The database is now created with liquibase instead of Hibernate and contains indices. My tests show that /deltaTree is now much faster (1 sec instead of a minute in my test)

**Comment by rzpio** [comment]
This should be fixed with the switch to Neo4j. Evaluate again after the switch.

**Comment by maximAtanasov** [comment]
No longer an issue after the refactoring.
