### ISSUE TITLE
Refactor Neo4J Database & Job Framework

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#204]
The jobs to analyze code are very complex. Is there a better way to analyze the codebase with the new Neo4J integration?

**Comment by thombergs** [comment]
Currently there are 4 Jobs (or so) working in choreography, which is hard to debug and maintain. These jobs have mainly been built this way to
* support parallel processing of jobs (which only works partly, anyways)
* keep a file identifiable over renames

Let's throw parallel processing over board for now.

As for keeping a file identifiable, we should be able to achieve that with this graph structure:

![graph](https://user-images.githubusercontent.com/1363578/53740532-b4264680-3e94-11e9-902f-42b44ebf1b7d.png)

The file names are not an attribute of the file node but instead an attribute of the change relationshipts between a file and a commit. This way, we should still be able to query for all file metrics we're interested in while we don't need to manually maintain file IDs anymore, because each File node IS a unique file.

We should be able to create a graph in one go, without having to go over the graph multiple times.

Also, let's throw away the job scheduling completely, for now. Instead, we implement a trigger that gets a commit as input. This trigger can be called via a web hook by GitHub, for example, when a new commit has been pushed. Coderadar then 
* builds the Graph up to this commit (if the previous commits have not been analyzed, yet)
* updates the Graph with only this commit (if all previous commits have already been analyzed)

For starters, we can trigger this via a button in the UI. Later, we can implement a job that checks for updates and does this automatically.

**Comment by rzpio** [comment]
First of all, I think it's good that we're throwing the job framework overboard for now. This allows us to concentrate on the core features of coderadar.

To the graph. I think it's good to use a _directed acyclic graph_ (DAG), a graph without circular dependencies. This saves us unnecessary sources of errors.
I like your graph, but I would like to make some suggestions. For this I have drawn an example graph.

![coderadar_graph](https://user-images.githubusercontent.com/33252305/53802919-6b799680-3f43-11e9-9f27-3235f0c256a4.png)

- One type of edge between a commit and a file is enough. Otherwise it becomes too complex with Neo4j-OGM. Instead, the edge has the property _changeType_, which consists of an enum (ADD, MODIFY, RENAME, ...). I would also direct the edge from the commit to the file. For example, this would allow us to analyze all files in a commit, starting from the commit.

- For example, I want to search for a file with a specific path. According to your graph, I would have to search all edges of files to commits for the corresponding file path. It would be easier to give the file node the _path_ property, i.e. the most current path of the file. If the path of the file is changed in a commit, the old path can be passed over the edge. The path of the file node can then be overwritten with the new path.

- You want to provide the values from the software metrics for each commit, don't you? With your graph, I could only read the most recent value. Since every commit has a timestamp anyway, I would make an edge from the file to the metric with the property _timestamp_. That would be the timestamp of the commit. This allows me to determine exactly which value of the file I want to have in which time period.

What do you think of the suggestions?

**Comment by thombergs** [comment]
Commit ID instead of timestamp as an indicator of which commit the metric value comes from.

**Comment by thombergs** [comment]
Depends on #202

**Comment by maximAtanasov** [comment]
The architecture and database shift is complete.
