### ISSUE TITLE
User password is sent in plaintext

### ISSUE THREAD

**Issue by maximAtanasov** [reflectoring/coderadar#232]
Passwords are sent to the server in plaintext. While this is fine when using HTTPS, a password could be intercepted otherwise. Maybe we should decide on a hash algorithm (MD5, SHA-2 ??) that we use on the client side as well. Maybe I'm wrong, I don't know if apps usually do it like this.

**Comment by thombergs** [comment]
Well, somehow, the password has to be sent to the server for verification. Using a hash algorithm on the client side doesn't help, since anyone else could also intercept this hashed password and then use it to verify against the server application. 

The only solution to this is client-to-server encryption with HTTPS.
